# Generated by Django 5.1.4 on 2025-02-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_online_dreamreal_online"),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "login",
            },
        ),
        migrations.RemoveField(
            model_name="dreamreal",
            name="online",
        ),
        migrations.DeleteModel(
            name="Online",
        ),
    ]
